# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='server',
  syntax='proto3',
  serialized_pb=_b('\n\x0cserver.proto\x12\x06server\"\x1c\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\r\".\n\tListReply\x12!\n\x08sessions\x18\x01 \x03(\x0b\x32\x0f.server.Session\"\x1d\n\nLeaveReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\rSetMaxPlayers\x12\x0e\n\x06number\x18\x01 \x01(\r\" \n\x0bJoinRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"*\n\x07Session\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\x81\x02\n\x0eSessionManager\x12)\n\x03new\x12\x0f.server.Session\x1a\x0f.server.Session\"\x00\x12.\n\x04join\x12\x13.server.JoinRequest\x1a\x0f.server.Session\"\x00\x12.\n\x05leave\x12\x0f.server.Session\x1a\x12.server.LeaveReply\"\x00\x12\x32\n\x06setMax\x12\x15.server.SetMaxPlayers\x1a\x0f.server.Session\"\x00\x12\x30\n\x04list\x12\x13.server.ListRequest\x1a\x11.server.ListReply\"\x00\x62\x06proto3')
)




_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='server.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='server.ListRequest.limit', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_LISTREPLY = _descriptor.Descriptor(
  name='ListReply',
  full_name='server.ListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessions', full_name='server.ListReply.sessions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=100,
)


_LEAVEREPLY = _descriptor.Descriptor(
  name='LeaveReply',
  full_name='server.LeaveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='server.LeaveReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=131,
)


_SETMAXPLAYERS = _descriptor.Descriptor(
  name='SetMaxPlayers',
  full_name='server.SetMaxPlayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='server.SetMaxPlayers.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=164,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='server.JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='server.JoinRequest.sessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=198,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='server.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='server.Session.sessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='server.Session.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=242,
)

_LISTREPLY.fields_by_name['sessions'].message_type = _SESSION
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ListReply'] = _LISTREPLY
DESCRIPTOR.message_types_by_name['LeaveReply'] = _LEAVEREPLY
DESCRIPTOR.message_types_by_name['SetMaxPlayers'] = _SETMAXPLAYERS
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTREQUEST,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.ListRequest)
  ))
_sym_db.RegisterMessage(ListRequest)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), dict(
  DESCRIPTOR = _LISTREPLY,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.ListReply)
  ))
_sym_db.RegisterMessage(ListReply)

LeaveReply = _reflection.GeneratedProtocolMessageType('LeaveReply', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEREPLY,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.LeaveReply)
  ))
_sym_db.RegisterMessage(LeaveReply)

SetMaxPlayers = _reflection.GeneratedProtocolMessageType('SetMaxPlayers', (_message.Message,), dict(
  DESCRIPTOR = _SETMAXPLAYERS,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.SetMaxPlayers)
  ))
_sym_db.RegisterMessage(SetMaxPlayers)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOINREQUEST,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.JoinRequest)
  ))
_sym_db.RegisterMessage(JoinRequest)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), dict(
  DESCRIPTOR = _SESSION,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.Session)
  ))
_sym_db.RegisterMessage(Session)



_SESSIONMANAGER = _descriptor.ServiceDescriptor(
  name='SessionManager',
  full_name='server.SessionManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=245,
  serialized_end=502,
  methods=[
  _descriptor.MethodDescriptor(
    name='new',
    full_name='server.SessionManager.new',
    index=0,
    containing_service=None,
    input_type=_SESSION,
    output_type=_SESSION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='join',
    full_name='server.SessionManager.join',
    index=1,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_SESSION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='leave',
    full_name='server.SessionManager.leave',
    index=2,
    containing_service=None,
    input_type=_SESSION,
    output_type=_LEAVEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setMax',
    full_name='server.SessionManager.setMax',
    index=3,
    containing_service=None,
    input_type=_SETMAXPLAYERS,
    output_type=_SESSION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='list',
    full_name='server.SessionManager.list',
    index=4,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_LISTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONMANAGER)

DESCRIPTOR.services_by_name['SessionManager'] = _SESSIONMANAGER

# @@protoc_insertion_point(module_scope)
